import fs from 'node:fs'
import path from 'node:path'
import vm from 'node:vm'
import ts from 'typescript'
import { pinyin } from 'pinyin-pro'

const ROOT = path.resolve(import.meta.dirname, '..')
const DATA = path.join(ROOT, 'src/data')
const sources = [
  ['emperors.ts', 'emperors'],
  ['figures.ts', 'figures'],
  ['events.ts', 'events'],
  ['classics-systems.ts', 'classicsAndSystems'],
  ['tang.ts', 'tangEntries'],
  ['song.ts', 'songEntries'],
  ['han.ts', 'hanEntries'],
  ['qing.ts', 'qingEntries']
]

const keep = [
  'id', 'type', 'name', 'pinyin', 'aliases', 'dynasty', 'era', 'lifespan',
  'summary', 'timeline', 'relations', 'quotes', 'sources', 'tags', 'image'
]

function loadArray(file, exportName) {
  const source = fs.readFileSync(path.join(DATA, file), 'utf8')
  const js = ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 }
  }).outputText
  const exports = {}
  vm.runInNewContext(`(function(exports){${js}\n})(exports)`, { exports })
  return exports[exportName]
}

const entries = sources.flatMap(([file, exportName]) =>
  loadArray(file, exportName).map(entry => ({ entry, source: file.replace(/\.ts$/, '') }))
)
const catalog = entries.map(({ entry, source }) => {
  const selected = Object.fromEntries(
    keep.filter(key => entry[key] !== undefined).map(key => [key, entry[key]])
  )
  selected.detailSource = source
  selected.interpretation = entry.interpretation?.slice(0, 420) ?? entry.summary
  selected.initials = pinyin(entry.name, { pattern: 'first', toneType: 'none', type: 'array' }).join('')
  return selected
})

const output = `// Generated by tools/generate-catalog.mjs. Do not edit manually.\nimport type { HistoryEntryCatalog } from '../types/history'\n\nexport const historyCatalog: HistoryEntryCatalog[] = ${JSON.stringify(catalog, null, 2)}\n`
fs.writeFileSync(path.join(DATA, 'catalog.ts'), output)
console.log(`Generated catalog: ${catalog.length} entries`)
