import fs from 'node:fs'
import path from 'node:path'
import vm from 'node:vm'
import ts from 'typescript'
import { pinyin } from 'pinyin-pro'

const ROOT = path.resolve(import.meta.dirname, '..')
const DATA = path.join(ROOT, 'src/data')
const sources = [
  ['emperors.ts', 'emperors'],
  ['figures.ts', 'figures'],
  ['events.ts', 'events'],
  ['classics-systems.ts', 'classicsAndSystems'],
  ['tang.ts', 'tangEntries'],
  ['song.ts', 'songEntries'],
  ['han.ts', 'hanEntries'],
  ['qing.ts', 'qingEntries']
]

/** 首屏核心目录字段：检索 / 星图 / 首页必需（timeline/interpretation/quotes/sources 走扩展包，勿加回） */
const keepCore = [
  'id', 'type', 'name', 'pinyin', 'aliases', 'dynasty', 'era', 'lifespan',
  'summary', 'tags', 'image'
]

function loadArray(file, exportName) {
  const source = fs.readFileSync(path.join(DATA, file), 'utf8')
  const js = ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 }
  }).outputText
  const exports = {}
  vm.runInNewContext(`(function(exports){${js}\n})(exports)`, { exports })
  return exports[exportName]
}

const entries = sources.flatMap(([file, exportName]) =>
  loadArray(file, exportName).map(entry => ({ entry, source: file.replace(/\.ts$/, '') }))
)

const catalog = entries.map(({ entry, source }) => {
  const selected = Object.fromEntries(
    keepCore.filter(key => entry[key] !== undefined).map(key => [key, entry[key]])
  )
  selected.detailSource = source
  // 关系瘦身：目录级消费方（星图 / 反向索引 / 关联推荐）只读 targetId + type
  if (entry.relations?.length) {
    selected.relations = entry.relations.map(r => ({ targetId: r.targetId, type: r.type }))
  }
  selected.initials = pinyin(entry.name, { pattern: 'first', toneType: 'none', type: 'array' }).join('')
  return selected
})

/** 扩展包：interpretation 截断版 + quotes + sources（问典 RAG / 首页今日词条，按 id 懒加载） */
const ext = {}
for (const { entry } of entries) {
  const rec = {}
  if (entry.interpretation) rec.interpretation = entry.interpretation.slice(0, 420)
  if (entry.quotes?.length) rec.quotes = entry.quotes
  if (entry.sources?.length) rec.sources = entry.sources
  if (rec.interpretation || rec.quotes || rec.sources) ext[entry.id] = rec
}

/** 史册残页池：全站词条编年节点拍平（首页残页 / 点墨捞史懒加载） */
const chronicle = entries.flatMap(({ entry }) =>
  (entry.timeline ?? []).map(n => ({
    year: n.year,
    event: n.event,
    entryId: entry.id,
    entryName: entry.name
  }))
)

/** 构建期站点统计（与源数据同源生成，audit-data 校验 chronicle 引用一致性） */
const quoteTotal = entries.reduce((n, { entry }) => n + (entry.quotes?.length ?? 0), 0)
const sourceTitles = new Set()
for (const { entry } of entries) {
  for (const s of entry.sources ?? []) {
    for (const m of s.matchAll(/《[^》]*》/g)) sourceTitles.add(m[0])
  }
}

const write = (file, content) => fs.writeFileSync(path.join(DATA, file), content)

write(
  'catalog.ts',
  `// Generated by tools/generate-catalog.mjs. Do not edit manually.\nimport type { HistoryEntryCatalog } from '../types/history'\n\nexport const historyCatalog: HistoryEntryCatalog[] = ${JSON.stringify(catalog, null, 2)}\n`
)
write(
  'catalog-ext.ts',
  `// Generated by tools/generate-catalog.mjs. Do not edit manually.\nimport type { CatalogExtRecord } from '../types/history'\n\n/** 懒加载扩展包（不进首屏目录）：问典 RAG 用 interpretation，首页今日词条用 quotes/sources。 */\nexport const catalogExt: Record<string, CatalogExtRecord> = ${JSON.stringify(ext, null, 2)}\n`
)
write(
  'chronicle.ts',
  `// Generated by tools/generate-catalog.mjs. Do not edit manually.\nimport type { ChronicleItem } from '../types/history'\n\n/** 史册残页池：全站词条编年节点拍平（首页懒加载）。 */\nexport const chroniclePool: ChronicleItem[] = ${JSON.stringify(chronicle, null, 2)}\n`
)
write(
  'siteStats.ts',
  `// Generated by tools/generate-catalog.mjs. Do not edit manually.\n\n/** 构建期站点统计（数据诚信：与源数据同源生成，改数据后跑 pnpm generate:catalog）。 */\nexport const siteStats = {\n  /** 全站史料引文总段数 */\n  quoteTotal: ${quoteTotal},\n  /** 引用史料种数（sources 去重书名号） */\n  sourceTitleCount: ${sourceTitles.size}\n} as const\n`
)

console.log(
  `Generated: catalog ${catalog.length} entries | ext ${Object.keys(ext).length} ids | chronicle ${chronicle.length} nodes | quotes ${quoteTotal} | sourceTitles ${sourceTitles.size}`
)
