// Generated by tools/generate-catalog.mjs. Do not edit manually.

/** 构建期站点统计（数据诚信：与源数据同源生成，改数据后跑 pnpm generate:catalog）。 */
export const siteStats = {
  /** 全站史料引文总段数 */
  quoteTotal: 966,
  /** 引用史料种数（sources 去重书名号） */
  sourceTitleCount: 252
} as const
